FROM node:12.2.0-alpine

WORKDIR /app

COPY package*.json ./

RUN yarn install

RUN yarn global add @quasar/cli

RUN yarn add express serve-static connect-history-api-fallback

COPY . .

RUN yarn build

CMD yarn start