version: "3.9"

services:
  api: 
    build:
      context: api/
      dockerfile: Django.Dockerfile
    command: bash django-entrypoint.sh
    volumes: 
      - ./api:/api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db  
  
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env

  client:
    build:
        context: ./client/
        dockerfile: Dockerfile
    command: quasar dev
    volumes:
        - ./client:/client
    ports:
        - 8080:8080
    depends_on:
        - api